[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "test2"
authors = [{name = "Adam St Arnaud", email = "adam@gensyn.ai"}]
dynamic = ["version", "description"]

[project.urls]
Home = "https://github.com/ajstarna/test2"
